version: "3"

services:
  server1:
    container_name: server1
    build:
      context: docker
      dockerfile: Dockerfile
    tty: true
    stdin_open: true

  server2:
    container_name: server2
    build:
      context: docker
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
